trendshop/trendshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("trendshop_website.urls")),
    path('', include("user.urls")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trendshop/trendshop_website/urls.py
from django.urls import path,include
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetCompleteView
from trendshop_website.views import home, OrderListView, \
    CartView, IncreaseItemQuantityView, DecreaseItemQuantityView, \
    RemoveItemFromCartView, OrderDeliveredStatusView, \
    OrderRefundedStatusView,add_to_cart,CheckoutView
from . import views
app_name = 'trendshop_website'

urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/', include('allauth.urls')),
    path('password-reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('category_list/', views.category_view, name='category_list'),
    path('category_list/<int:category_id>/subcategories/', views.subcategory_view, name='subcategory_list'),
    path('subcategory/<int:subcategory_id>/products/', views.product_view, name='product_list'),
    path('add/product/', views.add_product, name='add_product'),
    path('add/category/', views.add_category, name='add_category'),
    path('products/update/<int:product_id>/', views.product_update, name='product_update'),
    path('products/delete/<int:product_id>/', views.product_delete, name='product_delete'),
    path('product/<int:product_id>/', views.product_details, name='product_details'),

    path('add-to-cart/<int:product_id>/',views.add_to_cart, name='add_to_cart'),
    path('cart/', CartView.as_view(), name='cart'),
    path('increase-quantity/<int:pk>/', IncreaseItemQuantityView.as_view(), name='increase_quantity'),
    path('decrease-quantity/<int:pk>/', DecreaseItemQuantityView.as_view(), name='decrease_quantity'),
    path('remove-from-cart/<int:pk>/', RemoveItemFromCartView.as_view(), name='remove_from_cart'),

    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order/list/', OrderListView.as_view(), name='order_list'),
    path('order/status/delivered/<int:pk>/', OrderDeliveredStatusView.as_view(), name='delivered_status'),
    path('order/status/refunded/<int:pk>/', OrderRefundedStatusView.as_view(), name='refunded_status'),
]

trendshop/user/urls.py
from django.urls import path,include

from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, PasswordResetView, \
    PasswordResetConfirmView, PasswordChangeView, PasswordChangeDoneView, PasswordResetCompleteView


from user.views import SignupView, ProfileView, UserDeleteView, UserListView, \
    UserAddressCreateView, UserAddressListView, UserAddressUpdateView, UserAddressDeleteView, logout_view
from user.forms import LoginForm
from trendshop import settings




app_name = 'user'

urlpatterns = [

    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name="user/login.html",
                                     form_class=LoginForm), name='login'),
    path('logout/', logout_view, name='logout'),
    path('user/profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('password/reset/', PasswordResetView.as_view(), name='password_reset'),
    path('reset/<uidb64>/set-password,', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password/change/', PasswordChangeView.as_view(), name='password_change'),
    path('password/change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('user/delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    path('user/list/', UserListView.as_view(), name='user_list'),
    path('user-address/create/', UserAddressCreateView.as_view(), name='address_create'),
    path('user-address/list/', UserAddressListView.as_view(), name='address_list'),
    path('user-address/update/<int:pk>/', UserAddressUpdateView.as_view(), name='address_update'),
    path('user-address/delete/<int:pk>/', UserAddressDeleteView.as_view(), name='address_delete'),

]

trendshop/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0,
minimum-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>You & Me Shop</title>
<link rel="icon" type="image/x-icon" href="/media/logo.png">

<!--    Font Awesome-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<!--    Custom Css File-->
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'css/base.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'css/navbar.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'css/pagination.css' %}"/>

</head>
<body >
<header>
    {% include 'navbar.html' %}
</header>
<main class="mx-lg-5">
    <div class="container-fluid">
        {% block content %}
        {% endblock content %}
    </div>
</main>

{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}

{% block extrajs %}
<!--    javascript-->
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

<!--    jQuery-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock extrajs %}

</body>
</html>

trendshop/templates/footer.html
{% load static %}
<!-- Footer -->
{% if user.is_superuser or user.is_staff %}
<footer class="footer" style="margin-bottom: 0px">
    <div class="container">
        <div class="copyright">
            &copy; Copyright 2024 <strong><span style="color: #013b3b">You & Me Shop</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
            Designed by <strong style="color: #013b3b">Harshil Sidapara</strong>
        </div>
    </div>
</footer>
{% else %}
<footer id="footer" class="footer" style="background: rgba(108, 117, 125, 0.6)">

    <div class="container">
        <div class="row gy-3">
            <div class="col-lg-3 col-md-6 footer-links d-flex">
                <i class="fa-solid fa-location-dot fa-lg" style="color: #013b3b;"></i>&nbsp;
                <div>
                    <h4>Location</h4>
                    <p>
                        605, 6th floor, ABC Point,<br>
                        Iscon-Ambali Road, Ahmedabad - 380058<br>
                    </p>
                </div>

            </div>

            <div class="col-lg-3 col-md-6 footer-links d-flex">
                <i class="fa-solid fa-house" style="color: #013b3b;"></i>&nbsp;
                <div>
                    <h4>Get with Us</h4>
                    <p>
                        <i class="fa-solid fa-phone fa-lg" style="color: #013b3b;"></i>&nbsp;<strong style="color: #013b3b">:</strong> +91 9978819259<br>
                        <i class="fa-solid fa-envelope fa-lg" style="color: #013b3b;"></i>&nbsp;<strong style="color: #013b3b">:</strong> harshil.sidapara@trootech.com<br>
                    </p>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 footer-links d-flex">
                <i class="fa-solid fa-clock fa-lg" style="color: #013b3b;"></i>&nbsp;
                <div>
                    <h4>Open Hours (Delivery)</h4>
                    <p>
                        <strong style="color: #013b3b">Mon - Fri : </strong>10AM - 8PM<br>
                        <strong style="color: #013b3b">Sat - Sun : </strong>10AM - 2PM<br>
                    </p>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 footer-links d-flex">
                <i class="fa-solid fa-arrow-right fa-lg" style="color: #013b3b;"></i>&nbsp;
                <div>
                    <h4>Follow Us</h4>
                    <div class="social-links d-flex">
                        <a href="https://twitter.com/" class="twitter"><i class="fa-brands fa-twitter"></i></a>
                        <a href="https://www.facebook.com/" class="facebook"><i class="fa-brands fa-facebook-f"></i></a>
                        <a href="https://www.instagram.com/imharshil._.001" class="instagram"><i class="fa-brands fa-instagram"></i></a>
                    </div>
                    <br>
                    <h4><i class="fa-solid fa-calendar-days" style="color: #013b3b;">&nbsp;</i> Newsletter</h4>
                    <p>Enter email id for subscribing us to get all the latest updates.</p>
                    <div>
                        <form method="POST">
                            <div class="input-group mb-3 col-md-12">
                                <input type="email" class="form-control" aria-describedby="email-icon"
                                    style="margin-left: -20px;">
                                <span class="input-group-text" id="newsletter-send-icon">
                                    <i class="fa-solid fa-paper-plane" style="color: #0b7a72;"
                                        onclick="window.location.href='{% url 'trendshop_website:home' %}'"></i>
                                </span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="container">
        <div class="copyright">
            &copy; Copyright 2024 <strong><span style="color: #013b3b">You & Me Shop</span></strong> All Rights Reserved
        </div>
        <div class="credits">
            Designed by <strong style="color: #013b3b">Harshil Sidapara</strong>
        </div>
    </div>

</footer>
{% endif %}
<!-- End Footer -->

<link type="text/css" rel="stylesheet" href="{% static 'css/footer.css' %}" />

trendshop/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" style="background: rgba(108, 117, 125, 0.6)">
    <div class="container" id="header">
        <div class="row align-items-center">
            <div class="col-md-2" id="logo">
                <!-- Logo of a site -->
                <a href="{% url 'trendshop_website:home' %}"><img src="/media/logo.png" alt="company logo" width="100" height="100"></a>
            </div>
            <div class="col-lg-6">
                <!-- Navigation links -->
                <ul id="menu" class="d-flex justify-content-end mt-1" style="margin-left: 400px;">
                    <li>
                        <a href="{% url 'trendshop_website:cart' %}" id="cart"><i class="fa-solid fa-cart-shopping"></i> Cart </a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown" >
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img src="{{ user.image.url }}" class="rounded-circle" height="30" width="30"
                             loading="lazy"/>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item">
                            Hello, <b>{{user.first_name}}</b></a>
                            <a class="dropdown-item" href="{% url 'user:profile' user.id %}">
                                <i class="fa-regular fa-circle-user"></i> My Profile </a>
                            <a class="dropdown-item" href="{% url 'user:address_list' %}">
                                <i class="fa-regular fa-address-book"></i> My Addresses</a>
                            {% if user.is_superuser or user.is_staff %}
                            <a class="dropdown-item" href="{% url 'admin:index' %}">
                            <i class="fa-solid fa-globe"></i> Admin Site</a>
                            <a class="dropdown-item" href="{% url 'trendshop_website:home' %}">
                            <i class="fa-solid fa-globe"></i> My Site</a>
                            <a class="dropdown-item" href="{% url 'user:user_list' %}">
                            <i class="fa-solid fa-user"></i> User List</a>
                            {% endif %}
                             <div class="dropdown-divider"></div>
                            <a class="dropdown-item logout" id="logout-account" href="{% url 'user:logout' %}">
                                <i class="fa-regular fa-user"></i> Logout </a>
                        </div>
                    </li>
                    {% else %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Login/Sign Up </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'user:login' %}">
                                <i class="fa-regular fa-user"></i> Login </a>
                            <a class="dropdown-item" href="{% url 'user:signup' %}">
                                <i class="fa-solid fa-user-plus"></i> Sign Up </a>
                        </div>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
        <br>
    </div>
</nav>

trendshop/templates/pagination.html
{% load static %}
<!--Pagination-->
<div id="bottom_left_link" style="margin-top: 25px">
    <b style="color: rgba(11, 122, 114, 1)">Page
        <b style="color: #01514b">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</b>
    </b>
</div>
<div></div>
<div class="justify-content-end" id="bottom_link" aria-label="Page navigation example">
    <ul class="pagination justify-content-end">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link btn btn-secondary" href="?&page=1">
                <b class="text-dark">&laquo;</b></a></li>
        <li class="page-item"><a class="page-link btn btn-secondary" href="?&page={{ page_obj.previous_page_number }}">
                <b class="text-dark">Previous</b></a></li>
        {% endif %}
        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link btn btn-outline-secondary"
                href="?&page={{ page_obj.next_page_number }}">
                <b class="text-dark">Next</b></a></li>
        <li class="page-item"><a class="page-link btn btn-secondary" href="?&page={{ page_obj.paginator.num_pages }}">
                <b class="text-dark">&raquo;</b></a></li>
        {% endif %}
    </ul>
</div>
<!--End Pagination-->

trendshop/templates/website.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row">
<div class="container">
    <div class="category-container">
        {% for subcategory in subcategories %}
        <!-- Category Item 1 -->
        <div class="category-item" id="category-item">
            <img src="{{ subcategory.image.url}}" alt="{{ subcategory.title }}">
             <a href="{% url 'trendshop_website:subcategory_list' subcategory.id %}">{{ subcategory.title }}</a>
        </div>
        {% endfor %}
    </div>
</div>

<!--    Carousel-->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" id="carousel_slide">
        <div class="carousel-item active" >
            <img class="d-block w-100" src="{% static 'images/carousel_1.webp' %}" alt="First slide">
        </div>
        <div class="carousel-item" >
            <a href="{% url 'trendshop_website:product_list' 19 %}"><img class="d-block w-100" src="{% static 'images/carousel_2.webp' %}"  alt="Second slide"></a>
        </div>
        <div class="carousel-item">
            <a href="{% url 'trendshop_website:product_list' 11 %}"><img class="d-block w-100" src="{% static 'images/carousel_3.webp' %}"  alt="Third slide"></a>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<div class="container">
    <div class="row">
        <div class="card" style="width: 9rem;">
            <div class="card-body">
                <a href="{% url 'trendshop_website:product_details' 34 %}"><img src="{% static 'images/vivo_T3X.webp' %}"  alt="" height="145" width="113"></a>
                <div class="card-text-container">

                    <p style="text-align: center">Vivo T3X 5G</p>
                    <p style="text-align: center"><b>From ₹12,499</b></p>
                </div>
            </div>
        </div>
        <div class="card" style="width: 9rem;">
            <div class="card-body">
                <a href="{% url 'trendshop_website:product_details' 35 %}"><img src="{% static 'images/motorola_edge.webp' %}" alt="" height="145" width="113"></a>
                <div class="card-text-container">
                    <p style="text-align: center">Motorola Pro</p>
                    <p style="text-align: center"><b>From ₹27,999</b></p>
                </div>
            </div>
        </div>
        <div class="card" style="width: 9rem;">
            <div class="card-body">
                <a href="{% url 'trendshop_website:product_details' 36 %}"><img src="{% static 'images/galaxy_f15.webp' %}" alt="" height="145" width="113"></a>
                <div class="card-text-container">
                    <p style="text-align: center">Galaxy F15 </p>
                    <p style="text-align: center"><b>From ₹10,999</b></p>
                </div>
            </div>
        </div>
         <div class="card" style="width: 9rem;">
            <div class="card-body">
                <a href="{% url 'trendshop_website:product_details' 37 %}"><img src="{% static 'images/realme_p1.webp' %}" alt="" height="145" width="113"></a>
                <div class="card-text-container">
                    <p style="text-align: center">Realme P1</p>
                    <p style="text-align: center"><b>From ₹15,999</b></p>
                </div>
            </div>
        </div>
         <div class="card" style="width: 9rem;">
            <div class="card-body">
                <a href="{% url 'trendshop_website:product_details' 38 %}"><img src="{% static 'images/moto_g34.webp' %}" alt="" height="145" width="113"></a>
                <div class="card-text-container">
                    <p style="text-align: center">Moto G34</p>
                    <p style="text-align: center"><b>From ₹11,999</b></p>
                </div>
            </div>
        </div>
         <div class="card" style="width: 9rem;">
            <div class="card-body">
                <a href="{% url 'trendshop_website:product_details' 39 %}"><img src="{% static 'images/poco.webp' %}" alt="" height="145" width="113"></a>
                <div class="card-text-container">
                    <p style="text-align: center">Poco M6 Pro</p>
                    <p style="text-align: center"><b>From ₹9,999</b></p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Featured Brands -->
<div class="container">
    <div class="row" id="featured_carousel">
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel" data-interval="3000">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <a href="{% url 'trendshop_website:product_list' 32 %}"><img src="{% static 'images/featured4.webp' %}" class="d-block w-100" alt="First Slide"></a>
                    </div>
                    <div class="carousel-item">
                        <a href="{% url 'trendshop_website:product_list' 34 %}"><img src="{% static 'images/featured5.webp' %}" class="d-block w-100" alt="Second Slide"></a>
                    </div>
                    <div class="carousel-item">
                        <a href="{% url 'trendshop_website:product_list' 17 %}"><img src="{% static 'images/featured6.webp' %}" class="d-block w-100" alt="Third Slide"></a>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
        </div>
         <div id="carouselExampleControls2" class="carousel slide" data-ride="carousel" data-interval="3000">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <a href="{% url 'trendshop_website:subcategory_list' 2 %}"><img src="{% static 'images/featured1.webp' %}" class="d-block w-100 h-auto" alt="First Slide"></a>
                    </div>
                    <div class="carousel-item">
                        <a href="{% url 'trendshop_website:subcategory_list' 3 %}"><img src="{% static 'images/featured2.webp' %}" class="d-block w-100" alt="Second Slide"></a>
                    </div>
                    <div class="carousel-item">
                        <a href="{% url 'trendshop_website:product_list' 33 %}"><img src="{% static 'images/featured3.webp' %}" class="d-block w-100" alt="Third Slide"></a>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleControls2" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleControls2" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
        </div>
        <div id="carouselExampleControls3" class="carousel slide" data-ride="carousel" data-interval="3000">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <a href="{% url 'trendshop_website:subcategory_list' 5 %}"><img src="{% static 'images/featured7.webp' %}" class="d-block w-100" alt="First Slide"></a>
                    </div>
                    <div class="carousel-item">
                        <a href="{% url 'trendshop_website:subcategory_list' 10 %}"><img src="{% static 'images/featured8.webp' %}" class="d-block w-100" alt="Second Slide"></a>
                    </div>
                    <div class="carousel-item">
                        <a href="{% url 'trendshop_website:subcategory_list' 5 %}"><img src="{% static 'images/featured9.webp' %}" class="d-block w-100" alt="Third Slide"></a>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleControls3" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleControls3" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
        </div>
    </div>
</div>
</div>
<link type="text/css" rel="stylesheet" href="{% static 'css/website.css' %}"/>
{% endblock content %}