trendshop/trendshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("trendshop_website.urls")),
    path('', include("user.urls")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trendshop/trendshop_website/urls.py
from django.urls import path,include
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetCompleteView
from trendshop_website.views import home, OrderListView, \
    CartView, IncreaseItemQuantityView, DecreaseItemQuantityView, \
    RemoveItemFromCartView, OrderDeliveredStatusView, \
    OrderRefundedStatusView,add_to_cart,CheckoutView
from . import views
app_name = 'trendshop_website'

urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/', include('allauth.urls')),
    path('password-reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('category_list/', views.category_view, name='category_list'),
    path('category_list/<int:category_id>/subcategories/', views.subcategory_view, name='subcategory_list'),
    path('subcategory/<int:subcategory_id>/products/', views.product_view, name='product_list'),
    path('add/product/', views.add_product, name='add_product'),
    path('add/category/', views.add_category, name='add_category'),
    path('products/update/<int:product_id>/', views.product_update, name='product_update'),
    path('products/delete/<int:product_id>/', views.product_delete, name='product_delete'),
    path('product/<int:product_id>/', views.product_details, name='product_details'),

    path('add-to-cart/<int:product_id>/',views.add_to_cart, name='add_to_cart'),
    path('cart/', CartView.as_view(), name='cart'),
    path('increase-quantity/<int:pk>/', IncreaseItemQuantityView.as_view(), name='increase_quantity'),
    path('decrease-quantity/<int:pk>/', DecreaseItemQuantityView.as_view(), name='decrease_quantity'),
    path('remove-from-cart/<int:pk>/', RemoveItemFromCartView.as_view(), name='remove_from_cart'),

    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order/list/', OrderListView.as_view(), name='order_list'),
    path('order/status/delivered/<int:pk>/', OrderDeliveredStatusView.as_view(), name='delivered_status'),
    path('order/status/refunded/<int:pk>/', OrderRefundedStatusView.as_view(), name='refunded_status'),
]

trendshop/user/urls.py
from django.urls import path,include

from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, PasswordResetView, \
    PasswordResetConfirmView, PasswordChangeView, PasswordChangeDoneView, PasswordResetCompleteView


from user.views import SignupView, ProfileView, UserDeleteView, UserListView, \
    UserAddressCreateView, UserAddressListView, UserAddressUpdateView, UserAddressDeleteView, logout_view
from user.forms import LoginForm
from trendshop import settings




app_name = 'user'

urlpatterns = [

    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name="user/login.html",
                                     form_class=LoginForm), name='login'),
    path('logout/', logout_view, name='logout'),
    path('user/profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('password/reset/', PasswordResetView.as_view(), name='password_reset'),
    path('reset/<uidb64>/set-password,', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password/change/', PasswordChangeView.as_view(), name='password_change'),
    path('password/change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('user/delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    path('user/list/', UserListView.as_view(), name='user_list'),
    path('user-address/create/', UserAddressCreateView.as_view(), name='address_create'),
    path('user-address/list/', UserAddressListView.as_view(), name='address_list'),
    path('user-address/update/<int:pk>/', UserAddressUpdateView.as_view(), name='address_update'),
    path('user-address/delete/<int:pk>/', UserAddressDeleteView.as_view(), name='address_delete'),

]

trendshop/user/forms.py
"""
This file contains signup, login, profile and user address model forms which are used in
project.
"""

from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from user.models import User, UserAddress


class SignupForm(UserCreationForm):
    """
    This form will create user.
    """

    def __init__(self, *args, **kwargs):
        """
        This method will initialise custom class.
        """
        super(SignupForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
        self.fields['email'].required = True
        self.fields['gst'].required = False

    class Meta:
        """
        Model Meta is basically the inner class of your model class.
        Model Meta is basically used to change the behavior of your model fields like changing
        order options,verbose_name, and a lot of other options.
        """
        model = User
        fields = ['username', 'email', 'user_types','gst','phone_number', 'password1', 'password2']

    def clean(self):
        """
        This method will validate data from form.
        """
        cleaned_data = super(SignupForm, self).clean()
        email = self.cleaned_data.get('email')
        phone_number = self.cleaned_data.get('phone_number')
        validate_email(email)

        if User.objects.filter(email__iexact=email).exclude(id=self.instance.id).exists():
            raise ValidationError("Email already exists", code='invalid')
        if User.objects.filter(phone_number=phone_number).exclude(id=self.instance.id).exists():
            raise ValidationError("Phone number already exists", code='invalid')

        return cleaned_data


class LoginForm(AuthenticationForm):
    """
    This form will authenticate user.
    """

    def __init__(self, *args, **kwargs):
        """
        This method will initialise custom class.
        """
        super(LoginForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control form-control-lg'


class ProfileForm(forms.ModelForm):
    """
    This form will display user details.
    """

    def __init__(self, *args, **kwargs):
        """
        This method will initialise custom class.
        """
        super(ProfileForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
        self.fields['gender'].widget.attrs['class'] = 'select2 form-control'
        self.fields['email'].required = True

    class Meta:
        """
        Model Meta is basically the inner class of your model class.
        Model Meta is basically used to change the behavior of your model fields like changing
        order options,verbose_name, and a lot of other options.
        """
        model = User
        fields = ['first_name', 'last_name', 'username',
                  'email', 'gender', 'birth_date', 'image', 'phone_number']
        forms.DateInput.input_type = "date"
        widgets = {'image': forms.FileInput}


class UserAddressForm(forms.ModelForm):
    """
    This is model form of user address model.
    """

    def __init__(self, *args, **kwargs):
        """
        This method will initialise custom class.
        """
        super(UserAddressForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
        self.fields['type'].widget.attrs['class'] = 'select2 form-control'

    class Meta:
        """
        Model Meta is basically the inner class of your model class.
        Model Meta is basically used to change the behavior of your model fields like changing
        order options,verbose_name, and a lot of other options.
        """
        model = UserAddress
        fields = ['address', 'pincode', 'city', 'state', 'type']


class UserForm(forms.ModelForm):
    repassword = forms.CharField(required=True, label='Re-Enter Password',widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['user_types','first_name','last_name','email','password','gst','username','gender','phone_number']
        labels = {
            'first_name':'First Name',
            'last_name':'Last Name',
            'email':'Email Id',
            'gst':'GST No.',
            'username':'User Name',
            'password':'Password',
            'phone_number':'Phone Number'
        }
        widgets = {
            'password':forms.PasswordInput,
        }

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        repassword = cleaned_data.get("repassword")
        if password != repassword:
            raise forms.ValidationError("The Password do not match.")


    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['gst'].required = False

trendshop/user/views.py
from django.shortcuts import render,get_object_or_404
"""This file contains class based views for user and user address model."""

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, DeleteView, UpdateView, ListView
from django_filters.views import FilterView
from trendshop.views import CustomPermissionRequired
from user.filters import UserFilter
from user.forms import SignupForm, ProfileForm, UserAddressForm,UserForm
from user.models import User, UserAddress
from django.contrib.auth import logout


from django.utils.translation import gettext_lazy as _



class PasswordContextMixin:
    extra_context = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {"title": self.title, "subtitle": None, **(self.extra_context or {})}
        )
        return context

class SignupView(CreateView):
    """
    This class will create new user instance.
    """
    form_class = SignupForm
    template_name = 'user/signup.html'
    success_url = reverse_lazy('user:login')

    def post(self, request, *args, **kwargs):
        super(SignupView, self).post(request, *args, **kwargs)
        form = self.get_form()
        if form.is_valid():
            form.save()
            user_email = form.data['email']
            username = form.data['username']
            send_welcome_email.delay(user_email, username)
        else:
            return self.form_invalid(form)
        return redirect(self.success_url)


class ProfileView(UserPassesTestMixin, LoginRequiredMixin, UpdateView):
    """
    This class will update user if user is authenticated.
    """
    model = User
    form_class = ProfileForm
    template_name = 'user/profile.html'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse('user:profile', kwargs={'pk': pk})

    def test_func(self):
        """
        This method will check whether user has permission or not.
        """
        instance = self.get_object()
        if instance.id == self.request.user.id or self.request.user.is_superuser \
                or self.request.user.is_staff:
            return True


class UserDeleteView(UserPassesTestMixin, LoginRequiredMixin, DeleteView):
    """
    This class will delete user if user is authenticated.
    """
    model = User
    success_url = reverse_lazy('user:login')

    def test_func(self):
        """
        This method will check whether user has permission or not.
        """
        instance = self.get_object()
        if instance.id == self.request.user.id:
            return True


class UserListView(LoginRequiredMixin, CustomPermissionRequired, FilterView):
    """
    This class will return a list of all users only if user is superuser.
    """
    model = User
    template_name = 'user/user_list.html'
    context_object_name = 'users'
    filterset_class = UserFilter

    def get_queryset(self):
        """
        Returns a queryset of user.
        """
        query = self.request.GET.get('search')
        if query:
            return User.objects.filter(
                Q(first_name__icontains=query) | Q(last_name__icontains=query) |
                Q(username__icontains=query) | Q(email__iexact=query) |
                Q(phone_number__exact=query))
        return User.objects.all()


class UserAddressCreateView(CreateView):
    """
    This class will create user address.
    """
    form_class = UserAddressForm
    template_name = 'user/user_address_list.html'
    success_url = reverse_lazy('user:address_list')

    def post(self, request, *args, **kwargs):
        """
        This method will assign user to user address.
        """
        form = self.get_form(form_class=self.get_form_class())
        instance = form.save(commit=False)

        if form.is_valid():
            instance.user = request.user
        instance.save()
        return redirect(self.success_url)


class UserAddressListView(LoginRequiredMixin, ListView):
    """
    This class will return a list of addresses of specific user if user is authenticated.
    """
    model = UserAddress
    template_name = 'user/user_address_list.html'
    context_object_name = 'addresses'

    def get_context_data(self, *, object_list=None, **kwargs):
        """
        This method will pass extra context to template.
        """
        context = super(UserAddressListView, self).get_context_data(**kwargs)
        context['form'] = UserAddressForm
        return context

    def get_queryset(self):
        """
        Returns a queryset of user address of specific user.
        """
        return UserAddress.objects.filter(user=self.request.user)


class UserAddressUpdateView(UserPassesTestMixin, LoginRequiredMixin, UpdateView):
    """
    This class will update user address if user is authenticated.
    """
    model = UserAddress
    form_class = UserAddressForm
    template_name = 'user/user_address_update.html'
    success_url = reverse_lazy('user:address_list')

    def test_func(self):
        """
        This method will check whether user has permission or not.
        """
        instance = self.get_object()
        if instance.user.id == self.request.user.id:
            return True


class UserAddressDeleteView(UserPassesTestMixin, LoginRequiredMixin, DeleteView):
    """
    This class will delete user address if user is authenticated.
    """
    model = UserAddress
    success_url = reverse_lazy('user:address_list')

    def test_func(self):
        """
        This method will check whether user has permission or not.
        """
        instance = self.get_object()
        if instance.user.id == self.request.user.id:
            return True



def logout_view(request):
    logout(request)
    return redirect("trendshop_website:home")

trendshop/user/templates/user/login.html
<!doctype html>
{% load static %}
{% load widget_tweaks %}
{% load socialaccount %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        crossorigin="anonymous" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Courgette&display=swap">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/js/all.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <link href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css" rel="stylesheet">
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
    <link rel="icon" type="image/x-icon" href="/media/logo.png">
    <link type="text/css" rel="stylesheet" href="{% static 'css/user.css' %}" />
    <title>Login Page</title>
</head>

<body style="background: rgba(11, 122, 114, 0.2)">
    <section class="section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-12 col-lg-10">
                    <div class="wrap d-md-flex">
                        <img src="/media/logo.png" alt="logo_company">
                        <div class="login-wrap p-4 p-md-5">
                            <div class="d-flex">
                                <div class="w-100 d-flex align-items-center justify-content-center">
                                    <h3 style="color: rgba(11, 122, 114, 1)"><strong>LOGIN</strong></h3>
                                </div>
                            </div>
                            <div class="d-flex">
                                <div class="w-100 d-flex align-items-center justify-content-center">
                                    <p style="color: rgba(11, 122, 114, 1);font-family: Pacifico;font-size: 34px;">
                                        Welcome back!
                                    </p>
                                </div>
                            </div>
                            <form method="POST">
                                {% csrf_token %}
                                {% if form.errors %}
                                {% for key, error in form.errors.items %}
                                <h6>{{ error }}</h6>
                                {% endfor %}
                                {% endif %}
                                <label class="label" style="color: rgba(11, 122, 114, 1)">Username</label>
                                <div class="input-group mb-3">
                                    <span class="input-group-text" id="user-icon">
                                        <i class="fa-solid fa-user" style="color: #0b7a72;"></i>
                                    </span>
                                    {% render_field form.username aria-describedby="user-icon" %}
                                </div>
                                <label class="label" style="color: rgba(11, 122, 114, 1)">Password</label>
                                <div class="input-group mb-3">
                                    <span class="input-group-text" id="password-icon">
                                        <i class="fa-solid fa-lock" style="color: #0b7a72;"></i>
                                    </span>
                                    {% render_field form.password aria-describedby="password-icon" %}
                                </div>
                                <div class="form-group d-md-flex justify-content-end">
                                    <a href="{% url 'user:password_reset' %}" class="fw-bold"
                                        style="color: rgba(11, 122, 114, 1)">
                                        Forgot Password?
                                    </a>
                                </div>
                                <br>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-outline-secondary rounded w-100"
                                        style="background-color: rgba(11, 122, 114, 1);font-weight: bold;">Login
                                    </button>
                                </div>
                            </form>
                            <div class="align-items-center justify-content-center">
                                <p
                                    class="mt-2 fw-bold text-center text-secondary align-items-center justify-content-center">
                                    Don't have an account?
                                    <a href="{% url 'user:signup' %}" class="fw-bold">
                                        Signup</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>

</html>

trendshop/user/templates/user/password_reset_complete.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        crossorigin="anonymous" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Courgette&display=swap">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/js/all.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <link href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css" rel="stylesheet">
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
    <link rel="icon" type="image/x-icon" href="/media/logo.png">
    <link type="text/css" rel="stylesheet" href="{% static 'css/user.css' %}" />
    <title>Reset Password Complete</title>
</head>

<body style="background: rgba(11, 122, 114, 0.2)">
    <section class="section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-12 col-lg-10">
                    <div class="wrap d-md-flex">
                        <img src="/media/logo.png" alt="logo_company">
                        <div class="login-wrap p-4 p-md-5">
                            <div class="d-flex">
                                <div class="w-100 d-flex align-items-center justify-content-center">
                                    <h3 style="color: rgba(11, 122, 114, 1)"><strong>RESET PASSWORD COMPLETED</strong>
                                    </h3>
                                </div>
                            </div>
                            <br>
                            <div class="d-flex">
                                <div class="w-100 d-flex align-items-center justify-content-center">
                                    <p style="color: rgba(11, 122, 114, 1);font-family: Courgette;font-size: 24px;">
                                        Your password has been set. You may go ahead and login now.
                                    </p>
                                </div>
                            </div>
                            <br>
                            <br>
                            <br>
                            <br>
                            <br>
                            <br>
                            <br>
                            <br>
                            <br>
                            <br>
                            <br>
                            <div class="align-items-center justify-content-center">
                                <p class="mt-2 fw-bold text-center text-secondary align-items-center justify-content-center"
                                    style="font-size: 20px">
                                    <a href="{% url 'user:signup' %}" class="fw-bold">Signup | </a>
                                    <a href="{% url 'user:login' %}" class="fw-bold">Login</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>

</html>

trendshop/user/templates/user/password_reset_email.html
{% autoescape off %}
Hello {{ user.first_name }},

To initiate the password reset process for your {{ user.get_username }} You & Me Shop Account,
click the link below:

{{ protocol }}://192.168.0.190:8000{% url 'user:password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
You & Me Shop Team
{% endautoescape %}

trendshop/user/templates/user/user_address_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!--User Address List-->
{% if addresses %}
<div class="d-grid gap-2 d-md-flex justify-content-md-end" style="margin-top: 10px;">
    <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#exampleModal"><i
            class="fa fa-plus fa-lg"></i>
        Add Address
    </button>
</div>

{% for address in addresses %}
<div class="card col-7" style="background: rgba(223, 236, 248, 1); border-radius: 20px;">
    <div class="card-body">
        <h5 class="card-title">{{ address.type }}</h5>
        <p class="card-text">{{ address.address }} - {{ address.pincode }}</p>
        <p class="card-text">
            <small class="text">{{ address.city }},{{ address.state }}</small>
        </p>
    </div>
    <div class="card-footer">
        <div class="d-flex">
            <a class="btn btn-outline-primary w-100" style="margin-right: 10px;"
                href="{% url 'user:address_update' address.id %}">Edit address</a>
            <a class="btn btn-outline-danger w-100" style="margin-left: 10px;"
                href="{% url 'user:address_delete' address.id %}" data-bs-toggle="modal"
                data-bs-target="#DeleteModal{{ address.id }}">Delete</a>
        </div>
    </div>
    <!-- User Address Delete Modal -->
    <div class="modal fade" id="DeleteModal{{ address.id }}" tabindex="-1" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title fs-5">Delete Address</h3>
                    <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal"
                        aria-label="Close"><span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'user:address_delete' address.id %}" method="POST">
                        {% csrf_token %}
                        Are you sure you want to delete your address ?
                        <div class="modal-footer">
                            <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel
                            </button>
                            <button type="submit" class="btn btn-outline-danger">Delete</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
{% endfor %}

<br>
<br>
<br>
{% else %}
<div class="card mb-5" style="margin-top: 10px;">
    <div class="card-body p-4">
        <div style="margin: auto">
            <p class="mb-0 me-5">
                <span>
                    <strong style="color: rgba(11, 122, 114, 1);font-size: 20px;font-weight: bold;margin: auto">
                        You have not created any address.
                    </strong>
                    <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal"
                        data-bs-target="#exampleModal"><i class="fa fa-plus fa-lg"></i>
                        Create Address
                    </button>
                </span>
            </p>
        </div>
    </div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
{% endif %}

<!-- User Address Create Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Create Address</h5>
                <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <form action="{% url 'user:address_create' %}" method="POST">
                    {% csrf_token %}
                    {% if form.errors %}
                    {% for key, error in form.errors.items %}
                    {{ error }}
                    {% endfor %}
                    {% endif %}
                    {{ form.as_p }}
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel
                        </button>
                        <button type="submit" id="success" class="btn btn-outline-primary">Create</button>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>
<br>
<!--End User List-->

<link type="text/css" rel="stylesheet" href="{% static 'css/select2.css' %}" />
<script type="text/javascript" src="{% static 'js/modal_select2.js' %}"></script>
{% endblock content %}
{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}