trendshop/trendshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("trendshop_website.urls")),
    path('', include("user.urls")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trendshop/trendshop_website/urls.py
from django.urls import path,include
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetCompleteView
from trendshop_website.views import home, OrderListView, \
    CartView, IncreaseItemQuantityView, DecreaseItemQuantityView, \
    RemoveItemFromCartView, OrderDeliveredStatusView, \
    OrderRefundedStatusView,add_to_cart,CheckoutView
from . import views
app_name = 'trendshop_website'

urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/', include('allauth.urls')),
    path('password-reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('category_list/', views.category_view, name='category_list'),
    path('category_list/<int:category_id>/subcategories/', views.subcategory_view, name='subcategory_list'),
    path('subcategory/<int:subcategory_id>/products/', views.product_view, name='product_list'),
    path('add/product/', views.add_product, name='add_product'),
    path('add/category/', views.add_category, name='add_category'),
    path('products/update/<int:product_id>/', views.product_update, name='product_update'),
    path('products/delete/<int:product_id>/', views.product_delete, name='product_delete'),
    path('product/<int:product_id>/', views.product_details, name='product_details'),

    path('add-to-cart/<int:product_id>/',views.add_to_cart, name='add_to_cart'),
    path('cart/', CartView.as_view(), name='cart'),
    path('increase-quantity/<int:pk>/', IncreaseItemQuantityView.as_view(), name='increase_quantity'),
    path('decrease-quantity/<int:pk>/', DecreaseItemQuantityView.as_view(), name='decrease_quantity'),
    path('remove-from-cart/<int:pk>/', RemoveItemFromCartView.as_view(), name='remove_from_cart'),

    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order/list/', OrderListView.as_view(), name='order_list'),
    path('order/status/delivered/<int:pk>/', OrderDeliveredStatusView.as_view(), name='delivered_status'),
    path('order/status/refunded/<int:pk>/', OrderRefundedStatusView.as_view(), name='refunded_status'),
]

trendshop/user/urls.py
from django.urls import path,include

from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, PasswordResetView, \
    PasswordResetConfirmView, PasswordChangeView, PasswordChangeDoneView, PasswordResetCompleteView


from user.views import SignupView, ProfileView, UserDeleteView, UserListView, \
    UserAddressCreateView, UserAddressListView, UserAddressUpdateView, UserAddressDeleteView, logout_view
from user.forms import LoginForm
from trendshop import settings




app_name = 'user'

urlpatterns = [

    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name="user/login.html",
                                     form_class=LoginForm), name='login'),
    path('logout/', logout_view, name='logout'),
    path('user/profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('password/reset/', PasswordResetView.as_view(), name='password_reset'),
    path('reset/<uidb64>/set-password,', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password/change/', PasswordChangeView.as_view(), name='password_change'),
    path('password/change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('user/delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    path('user/list/', UserListView.as_view(), name='user_list'),
    path('user-address/create/', UserAddressCreateView.as_view(), name='address_create'),
    path('user-address/list/', UserAddressListView.as_view(), name='address_list'),
    path('user-address/update/<int:pk>/', UserAddressUpdateView.as_view(), name='address_update'),
    path('user-address/delete/<int:pk>/', UserAddressDeleteView.as_view(), name='address_delete'),

]

trendshop/trendshop_website/forms.py
from django import forms
from trendshop_website.models import CartItem, Order
from user.models import UserAddress

from trendshop_website.models import Category,Product


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['image','title', 'description','parent']



class ProductsForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title', 'description', 'categories', 'price', 'image','stock']



class AddToCartForm(forms.ModelForm):
    quantity = forms.IntegerField(min_value=1, max_value=20,
                                  widget=forms.NumberInput(attrs={'class': 'form-control'}))

    class Meta:
        model = CartItem
        fields = ['quantity']


class OrderAddressForm(forms.ModelForm):
    delivery_address = forms.ModelChoiceField(queryset=UserAddress.objects.all(),
                                              widget=forms.Select(attrs={'class': 'select2 form-control'}))

    class Meta:
        model = Order
        fields = ['delivery_address']

trendshop/trendshop_website/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required, user_passes_test

from trendshop.views import CustomPermissionRequired
from .forms import ProductsForm,CategoryForm
from .utils import is_seller
from .models import Category,Product

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q, Count, Sum
from django.http import JsonResponse
from django.urls import reverse_lazy, reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView, TemplateView, ListView
from django_filters.views import FilterView
from trendshop.views import CustomPermissionRequired
from trendshop_website.filters import OrderFilter
from trendshop_website.forms import OrderAddressForm, AddToCartForm
from trendshop_website.models import Order, Cart, CartItem
from user.models import User

def home(request):
    subcategory = Category.objects.filter(parent__isnull=True)
    return render(request, 'website.html',{'subcategories': subcategory})

def category_view(request):
    parent_category = Category.objects.filter(parent__isnull=True)
    return render(request, 'trendshop_website/category_list.html', {'categories': parent_category})

def subcategory_view(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    subcategory = Category.objects.filter(parent=category)
    return render(request, 'trendshop_website/subcategory_list.html', {'categories': category,'subcategories': subcategory})

def product_view(request, subcategory_id):
    subcategory = get_object_or_404(Category, id=subcategory_id)
    products = Product.objects.filter(categories=subcategory)
    return render(request, 'trendshop_website/product_list.html', {'subcategory': subcategory, 'products': products})

@login_required
@user_passes_test(is_seller)
def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('trendshop_website:category_list')
    else:
        form = CategoryForm()
    return render(request, 'trendshop_website/category_add.html', {'form' : form})

@login_required
@user_passes_test(is_seller)
def add_product(request):
    if request.method == 'POST':
        form = ProductsForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('trendshop_website:category_list')  # Redirect to a list of products or another relevant page
    else:
        form = ProductsForm()
    return render(request, 'trendshop_website/product_add.html', {'form': form})


def product_update(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    form = ProductsForm(instance=product)
    subcategory = product.categories.first()
    if subcategory:
        subcategory_id = subcategory.id
    else:
        subcategory_id = None
    if request.method == 'POST':
        form = ProductsForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('trendshop_website:product_list', subcategory_id=subcategory_id)
    return render(request, 'trendshop_website/product_update.html', {'form': form, 'product': product})


def product_delete(request,product_id):
    product = get_object_or_404(Product, id=product_id)
    subcategory = product.categories.first()
    if subcategory:
        subcategory_id = subcategory.id
    else:
        subcategory_id = None
    product.delete()
    if subcategory_id:
        return redirect('trendshop_website:product_list', subcategory_id=subcategory_id)
    else:
        return redirect('trendshop_website:category_list')

def product_details(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    return render(request, 'trendshop_website/product_detail.html', {"product":product})





def add_to_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    cart,_ = Cart.objects.get_or_create(user=request.user)
    cart, created = CartItem.objects.get_or_create(item=product,user=request.user,cart=cart)
    cart.quantity += 1
    cart.save()
    success_url = reverse("trendshop_website:cart")
    return JsonResponse({"status": "success", "message": "Added To Cart","success_url":success_url})


class CartView(LoginRequiredMixin, ListView):
    model = Cart
    template_name = 'trendshop_website/cart.html'
    context_object_name = 'carts'

    def get_queryset(self):
        return Cart.objects.filter(user=self.request.user, status=True)



class IncreaseItemQuantityView(LoginRequiredMixin, UpdateView):
    model = CartItem

    def get(self, request, *args, **kwargs):
        cart_item = get_object_or_404(CartItem, id=kwargs['pk'])
        cart_item.quantity += 1
        cart_item.save()
        return redirect('trendshop_website:cart')

    def post(self, request, *args, **kwargs):
        super(IncreaseItemQuantityView, self).post(request, *args, **kwargs)
        return JsonResponse({'data': 'data'})


class DecreaseItemQuantityView(LoginRequiredMixin, UpdateView):
    model = CartItem

    def get(self, request, *args, **kwargs):
        cart_item = get_object_or_404(CartItem, id=kwargs['pk'])
        if cart_item.quantity < 2:
            cart_item.delete()
        else:
            cart_item.quantity -= 1
            cart_item.save()
        return redirect('trendshop_website:cart')


class RemoveItemFromCartView(LoginRequiredMixin, DeleteView):
    model = CartItem

    def get(self, request, *args, **kwargs):
        cart_item = get_object_or_404(CartItem, id=kwargs['pk'])
        cart_item.delete()
        return redirect('trendshop_website:cart')


class CheckoutView(LoginRequiredMixin, CreateView):
    form_class = OrderAddressForm
    template_name = 'trendshop_website/checkout.html'
    success_url = reverse_lazy('trendshop_website:payment')

    def get_context_data(self, **kwargs):
        context = super(CheckoutView, self).get_context_data(**kwargs)
        form = self.get_form()
        form.fields['delivery_address'].queryset = self.request.user.addresses.all()
        context.update({
            'form': form,
            'carts': Cart.objects.filter(user=self.request.user, status=True)
        })
        return context



















class OrderListView(LoginRequiredMixin, FilterView):
    model = Order
    template_name = 'trendshop_website/order_list.html'
    context_object_name = 'orders'
    filterset_class = OrderFilter
    paginate_by = 9

    def get_queryset(self):
        query = self.request.GET.get('search')
        if self.request.user.is_superuser or self.request.user.is_staff:
            if query:
                return Order.objects.filter(
                    Q(order__icontains=query) |
                    Q(status__icontains=query) |
                    Q(user__username__icontains=query) | Q(user__email__icontains=query))
            else:
                return Order.objects.all().order_by('-created')
        else:
            if query:
                return Order.objects.filter(Q(order__icontains=query))
            else:
                return Order.objects.filter(user=self.request.user).order_by('-created')


class OrderDeliveredStatusView(LoginRequiredMixin, CustomPermissionRequired, UpdateView):
    model = Order

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse('trendshop_website:order_detail', kwargs={'pk': pk})

    def get(self, request, *args, **kwargs):
        order = get_object_or_404(Order, id=kwargs['pk'])
        order.status = 'Delivered'
        order.save()
        return redirect(self.get_success_url())


class OrderRefundedStatusView(LoginRequiredMixin, CustomPermissionRequired, UpdateView):
    model = Order

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse('trendshop_website:order_detail', kwargs={'pk': pk})

    def get(self, request, *args, **kwargs):
        order = get_object_or_404(Order, id=kwargs['pk'])
        order.status = 'Deleted'
        order.save()
        return redirect(self.get_success_url())


class OrderDetailView(UserPassesTestMixin, LoginRequiredMixin, DetailView):
    model = Order
    template_name = 'trendshop_website/order_detail.html'
    context_object_name = 'order'

    def get(self, request, *args, **kwargs):
        cart, _ = Cart.objects.get_or_create(user=self.request.user, status=True)
        return super().get(request)

    def test_func(self):
        instance = self.get_object()
        if instance.user.id == self.request.user.id or self.request.user.is_superuser \
                or self.request.user.is_staff:
            return True

trendshop/trendshop_website/templates/trendshop_website/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% for cart in carts %}
{% if cart.carts.all %}
<div class="card" style="margin-top: 20px;">
    <div class="row">
        <div class="col-md-12 cart">
            <div class="title">
                <div class="row">
                    <div class="col">
                        <h3 style="color: rgba(11, 122, 114, 1)">CART DETAILS</h3>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="row main align-items-center">
                    <div class="col-2">
                        <h5 style="color: rgba(11, 122, 114, 1);margin-left: 15px;">Image</h5>
                    </div>
                    <div class="col">
                        <h5 style="color: rgba(11, 122, 114, 1)">Product Item</h5>
                    </div>
                    <div class="col">
                        <h5 style="color: rgba(11, 122, 114, 1);margin-left: 10px;">Price</h5>
                    </div>
                    <div class="col">
                        <h5 style="color: rgba(11, 122, 114, 1)">Quantity</h5>
                    </div>
                    <div class="col">
                        <h5 style="color: rgba(11, 122, 114, 1)">Subtotal</h5>
                    </div>
                    <div class="col">
                        <h5 style="color: rgba(11, 122, 114, 1)"></h5>
                    </div>
                </div>
            </div>
            {% for item in cart.carts.all %}
            <div class="row border-top">
                <div class="row main align-items-center">
                    <div class="col-2">
                        <img class="img-fluid" src="{{ item.item.image.url }}" alt="Product Image"
                            style="width: 100px; height: 100px;border-radius: 10px;" />
                    </div>
                    <div class="col">
                        <p class="mb-1" style="font-size: 15px;margin-left: 3px;">{{ item.item }}</p>
                    </div>
                    <div class="col">
                        <div class="row"><b>₹ {{ item.item.price }}</b></div>
                    </div>
                    <div class="col">
                        <div class="input-group mb-3" style="max-width:85px">
                            <div>
                                <i class="fa-solid fa-minus fa-sm text-secondary" id="decreaseQuantity"
                                    onclick="location.href='{% url 'trendshop_website:decrease_quantity' item.id %}'">
                                </i>
                                &nbsp;
                                <b id="quantity">{{ item.quantity }}</b>
                                &nbsp;
                                <i class="fa fa-plus fa-lg" id="increaseQuantity" style="color: rgba(11, 122, 114, 1)"
                                    onclick="location.href='{% url 'trendshop_website:increase_quantity' item.id %}'">
                                </i>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        ₹ {{ item.sub_total }}
                    </div>
                    <div class="col">
                        <a href="{% url 'trendshop_website:remove_from_cart' item.id %}">
                            <i class="fa-solid fa-trash-can fa-lg text-danger"></i>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<br>
<div class="card mb-5">
    <div class="card-body p-4">
        <div class="float-end">
            <p class="mb-0 me-5 d-flex align-items-center">
                <span style="color: rgba(11, 122, 114, 1);font-size: 20px;font-weight: bold;">Cart Total:&nbsp;</span>
                <span class="lead fw-normal">₹ {{ cart.cart_total }}</span>
            </p>
        </div>
    </div>
</div>
<div style="display: flex; justify-content:flex-end">
    <div style="display: flex; justify-content:flex-end">
        <a class="btn btn-outline-primary" href="{% url 'trendshop_website:category_list' %}"
            style="margin-right: 50px;)">Add Product</a>
        <a class="btn btn-outline-primary" href="{% url 'trendshop_website:checkout' %}">Proceed to Checkout</a>
    </div>
</div>
<br>
{% else %}
<div class="card mb-5">
    <div class="card-body p-4">
        <div style="margin: auto">
            <p class="mb-0 me-5">
                <span>
                    <strong style="color: rgba(11, 122, 114, 1);font-size: 20px;font-weight: bold;margin: auto">
                        There are no product in your cart.
                    </strong>
                    <a class="btn btn-outline-primary" href="{% url 'trendshop_website:category_list' %}"
                        style="margin: 0px 0px 0px 500px;">Add products</a>
                </span>
            </p>
        </div>
    </div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
{% endif %}
{% endfor %}

<link type="text/css" rel="stylesheet" href="{% static 'css/cart.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'css/select2.css' %}" />
<script src="{% static 'js/modal_select2.js' %}"></script>
<script src="{% static 'js/toast.js' %}"></script>
<script src="{% static 'trendshop_website/js/increase_quantity.js' %}"></script>
{% endblock content %}
{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}

trendshop/trendshop_website/templates/trendshop_website/category_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" id="categories">
    <h1 class="my-4">Categories</h1>
    {% if user.is_authenticated and user.user_types == "seller" %}
    <a href="{% url 'trendshop_website:add_product' %}" class="btn btn-outline-primary">Add Product</a>
    <a href="{% url 'trendshop_website:add_category' %}" class="btn btn-outline-primary">Add Sub-Category</a>
    {% endif %}
    <div class="row">
        {% for category in categories %}
            <div class="col-md-4 mb-4">
                <div class="card h-100 custom-card">
                    <a href="{% url 'trendshop_website:subcategory_list' category.id %}">
                        <img class="card-img-top custom-card-img" src="{{ category.image.url }}" alt="{{ category.title }}">
                    </a>
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href="{% url 'trendshop_website:subcategory_list' category.id %}">{{ category.title }}</a>
                        </h5>
                        <p class="card-text">{{ category.description }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>
</div>
<link type="text/css" rel="stylesheet" href="{% static 'css/website.css' %}" />
{% endblock content %}

trendshop/trendshop_website/templates/trendshop_website/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container my-5">
    <div class="row">
        <div class="col-md-6">
            <div class="product-image">
                <img src="{{ product.image.url }}" alt="{{ product.title }}" class="img-fluid">
            </div>
        </div>
        <div class="col-md-6">
            <div class="product-details">
                <h1 class="product-title">{{ product.title }}</h1>
                <p class="product-description">{{ product.description }}</p>
                <div class="product-info">
                    <p class="product-price">Price: ₹{{ product.price }}</p>
                    <p class="product-stock">Stock: {{ product.stock }}</p>
                </div>
                <div class="product-actions">
                    {% if user.is_authenticated and user.user_types == "buyer" %}
                        <a class="btn btn-outline-danger" href='#'>Buy Now</a>
                         {% csrf_token %}
                        <button type="submit" id="add-to-cart-button" data-link="{% url 'trendshop_website:add_to_cart' product.id %}" class="btn btn-outline-primary">Add To Cart</button>
                    {% elif user.is_authenticated and user.user_types == "seller" %}
                        <button class="btn btn-outline-primary" data-bs-toggle="modal"
                            data-bs-target="#editModal{{ product.id }}"><i class="fa fa-edit fa-lg"></i> Edit
                        </button>
                        <button class="btn btn-outline-danger" data-bs-toggle="modal"
                            data-bs-target="#DeleteModal{{ product.id }}"><i class="fa fa-trash-can fa-lg"></i> Delete
                        </button>
                    {% else %}
                        <a class="btn btn-outline-danger" href="{% url 'user:login' %}">Buy Now</a>
                        <a class="btn btn-outline-primary" href="{% url 'user:login' %}">Add to Cart</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Product Delete Modal -->

<div class="modal fade" id="DeleteModal{{ product.id }}" tabindex="-1" aria-labelledby="exampleModalLabel"
     data-toggle="modal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title fs-5">Delete Product</h3>
               <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal"
                    aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete <b>{{ product.title }}</b> ?
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-dark"
                            data-bs-dismiss="modal">Cancel
                    </button>
                    <form action="{% url 'trendshop_website:product_delete' product.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-danger">
                            Delete
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!--  Product Update Modal-->
<div class="modal fade" id="editModal{{ product.id }}" tabindex="-1" role="dialog" aria-labelledby="editModalLabel{{ product.id }}"
     data-toggle="modal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="editModalLabel">Edit Product</h3>
                <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal"
                                aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to edit <strong>{{ product.title }}</strong>?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal">Cancel</button>
                <a href="{% url 'trendshop_website:product_update' product.id %}" class="btn btn-outline-primary">Edit</a>
            </div>
        </div>
    </div>
</div>

<style>
    .product-image {
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        overflow: hidden;
    }

    .product-image img {
        width: 100%;
        height: auto;
        object-fit: cover;
    }

    .product-details {
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        padding: 30px;
    }

    .product-title {
        font-size: 1.8rem;
        font-weight: bold;
        margin-bottom: 20px;
    }

    .product-description {
        font-size: 1.0rem;
        color: #666;
        margin-bottom: 30px;
    }

    .product-info {
        display: flex;
        justify-content: space-between;
        margin-bottom: 30px;
    }

    .product-price,
    .product-stock {
        font-size: 1.2rem;
        font-weight: bold;
    }

    .product-actions {
        display: flex;
        justify-content: space-evenly;
    }


</style>
{% endblock %}

{% block extrajs %}
{{ block.super }}
<script src="/static/trendshop_website/js/add_to_cart.js"></script>
{% endblock extrajs %}

trendshop/trendshop_website/templates/trendshop_website/product_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container" id="product-list">
    <h1 class="my-4">Product List</h1>
    {% if user.is_authenticated and user.user_types == "seller" %}
        <a href="{% url 'trendshop_website:add_product' %}" class="btn btn-outline-primary">Add Product</a>
    {% endif %}
    <div class="row custom-row">
        {% for product in products %}
            <div class="col-md-4 mb-4">
                <div class="card h-100 custom-card">
                    <a href="{% url 'trendshop_website:product_details' product.id %}" target="_blank"><img class="card-img-top custom-card-img" src="{{ product.image.url }}" alt="{{ product.title }}"></a>
                    <div class="card-footer">
                        <h5 class="card-title custom-card-title">{{ product.title }}</h5>
                        <p class="product-price">Price: ₹{{ product.price }}</p>
                    </div>
                </div>
            </div>

            <!-- Product Delete Modal -->

            <div class="modal fade" id="DeleteModal{{ product.id }}" tabindex="-1" aria-labelledby="exampleModalLabel"
                 data-toggle="modal" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h3 class="modal-title fs-5">Delete Product</h3>
                           <button type="button" class="btn btn-outline-primary" data-bs-dismiss="modal"
                                aria-label="Close"><span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            Are you sure you want to delete <b>{{ product.title }}</b> ?
                            <div class="modal-footer">
                                <button type="button" class="btn btn-outline-dark"
                                        data-bs-dismiss="modal">Cancel
                                </button>
                                <form action="{% url 'trendshop_website:product_delete' product.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-outline-danger">
                                        Delete
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
<!--            Product Update Modal-->
            <div class="modal fade" id="editModal{{ product.id }}" tabindex="-1" role="dialog" aria-labelledby="editModalLabel{{ product.id }}"
                 data-toggle="modal" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h3 class="modal-title" id="editModalLabel">Edit Product</h3>
                            <button type="button" class="btn btn-outline-primary" data-bs-dismiss="modal"
                                aria-label="Close"><span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            Are you sure you want to edit <strong>{{ product.title }}</strong>?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal">Cancel</button>
                            <a href="{% url 'trendshop_website:product_update' product.id %}" class="btn btn-outline-primary">Edit</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>
</div>
<script src="{% static 'js/toast.js' %}"></script>
<script src="{% static 'js/modal_select2.js' %}"></script>
<link type="text/css" rel="stylesheet" href="{% static 'css/website.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'css/select2.css' %}"/>
<link type="text/css" rel="stylesheet" href="{% static 'css/cart.css' %}"/>
{% endblock content %}